# Generated by Django 4.1.2 on 2022-10-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MInfo",
            new_name="TPersonData",
        ),
        migrations.RenameModel(
            old_name="MStandardClass",
            new_name="TStandardClass",
        ),
        migrations.RenameField(
            model_name="tstudent",
            old_name="info",
            new_name="person_data",
        ),
        migrations.RenameField(
            model_name="tteacher",
            old_name="info",
            new_name="person_data",
        ),
        migrations.RenameIndex(
            model_name="tpersondata",
            new_name="m_person_data_index",
            old_name="m_info_index",
        ),
        migrations.RenameIndex(
            model_name="tstandardclass",
            new_name="t_standard_class_index",
            old_name="m_standard_class_index",
        ),
        migrations.AlterModelTable(
            name="tpersondata",
            table="m_person_data",
        ),
        migrations.AlterModelTable(
            name="tstandardclass",
            table="t_standard_class",
        ),
    ]
